ExamApp/Areas/Admin/Controllers/ChefController.cs
using Business.Exceptions;
using Business.Services.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExamApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class ChefController : Controller
    {
        IChefService _chefService;

        public ChefController(IChefService chefService)
        {
            _chefService = chefService;
        }

        public IActionResult Index()
        {
            var chefs = _chefService.GetAll();
            return View(chefs);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Chef chef)
        {
            if (!ModelState.IsValid) return View();

            try
            {
                _chefService.Add(chef);
            }
            catch(FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return View();
            }
            catch (ContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (PhotoNullException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (ChefNullException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            if(!ModelState.IsValid) return View();
            var existChef = _chefService.Get(x=>x.Id == id);
            try
            {
                _chefService.Delete(id);
            }
            catch(Business.Exceptions.FileNotFoundException ex)
            {
                return NotFound();
            }
            catch(ChefNotFoundException ex)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            var existChef = _chefService.Get(x => x.Id == id);
            if(existChef == null) return NotFound();
            return View(existChef);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Chef chef)
        {
            if(!ModelState.IsValid) return View(); 
            try
            {
                _chefService.Update(chef.Id, chef);
            }
            catch (FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (ContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (ChefNullException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (ChefNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ExamApp/Areas/Admin/Views/Chef/Create.cshtml
@using Core.Models
@model Chef

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Fullname" class="form-label">Fullname</label>
            <input asp-for="Fullname" class="form-control" >
            <span asp-validation-for="Fullname" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" class="form-control">
            <span asp-validation-for="Description" style="color:red"></span>
        </div> 
        <div class="mb-3">
            <label asp-for="PhotoFile" class="form-label">Photo</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

ExamApp/Areas/Admin/Views/Chef/Index.cshtml
@using Core.Models
@model List<Chef>

@{
    int count = 0;
}

<div class="container">
    <table class="table">
        <h2>
            Chefs
            <a  class="btn btn-primary" asp-action="Create">Create</a>
        </h2>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Fullname</th>
                <th scope="col">Description</th>
                <th scope="col">Image</th>
                <th scope="col">Processing</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.Id</td>
                    <td>@item.Fullname</td>
                    <td>@item.Description</td>

                    <td>
                        <div style="width:100px">
                            <img style="width:100% " src="~/uploads/@item.ImgUrl"></img>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-warning" asp-action="Update" asp-controller="Chef" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Chef" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
            
        </tbody>
    </table>

</div>

ExamApp/Areas/Admin/Views/Chef/Update.cshtml
@using Core.Models
@model Chef

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Fullname" class="form-label">Fullname</label>
            <input asp-for="Fullname" class="form-control">
            <span asp-validation-for="Fullname" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" class="form-control">
            <span asp-validation-for="Description" style="color:red"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PhotoFile" class="form-label">Photo</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>